# Generated by Django 4.2 on 2025-05-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_user_address_user_contact_no_user_dob_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
